"""empty message

Revision ID: f3b4bd1ef407
Revises: e83fdca5a6d0
Create Date: 2025-10-30 17:29:41.408331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b4bd1ef407'
down_revision = 'e83fdca5a6d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('is_complete')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
